// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message.proto
// Protobuf C++ Version: 7.34.1

#ifndef message_2eproto_2epb_2eh
#define message_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_message_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_message_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_message_2eproto;
}  // extern "C"
namespace bus {
class IoConfig;
struct IoConfigDefaultTypeInternal;
extern IoConfigDefaultTypeInternal _IoConfig_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull IoConfig_class_data_;
class portCh;
struct portChDefaultTypeInternal;
extern portChDefaultTypeInternal _portCh_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull portCh_class_data_;
}  // namespace bus
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace bus {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED portCh final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:bus.portCh) */ {
 public:
  inline portCh() : portCh(nullptr) {}
  ~portCh() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(portCh* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(portCh));
  }
#endif

  template <typename = void>
  explicit constexpr portCh(::google::protobuf::internal::ConstantInitialized);

  inline portCh(const portCh& from) : portCh(nullptr, from) {}
  inline portCh(portCh&& from) noexcept
      : portCh(nullptr, ::std::move(from)) {}
  inline portCh& operator=(const portCh& from) {
    CopyFrom(from);
    return *this;
  }
  inline portCh& operator=(portCh&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const portCh& default_instance() {
    return *reinterpret_cast<const portCh*>(
        &_portCh_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(portCh& a, portCh& b) { a.Swap(&b); }
  inline void Swap(portCh* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(portCh* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] portCh* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<portCh>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const portCh& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const portCh& from) { portCh::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(portCh* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "bus.portCh"; }

  explicit portCh(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  portCh(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const portCh& from);
  portCh(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, portCh&& from) noexcept
      : portCh(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBaudFieldNumber = 1,
    kDataFieldNumber = 2,
    kStopFieldNumber = 3,
    kParityFieldNumber = 4,
    kFlowFieldNumber = 5,
  };
  // int32 baud = 1;
  void clear_baud() ;
  [[nodiscard]] ::int32_t baud() const;
  void set_baud(::int32_t value);

  private:
  ::int32_t _internal_baud() const;
  void _internal_set_baud(::int32_t value);

  public:
  // int32 data = 2;
  void clear_data() ;
  [[nodiscard]] ::int32_t data() const;
  void set_data(::int32_t value);

  private:
  ::int32_t _internal_data() const;
  void _internal_set_data(::int32_t value);

  public:
  // int32 stop = 3;
  void clear_stop() ;
  [[nodiscard]] ::int32_t stop() const;
  void set_stop(::int32_t value);

  private:
  ::int32_t _internal_stop() const;
  void _internal_set_stop(::int32_t value);

  public:
  // int32 parity = 4;
  void clear_parity() ;
  [[nodiscard]] ::int32_t parity() const;
  void set_parity(::int32_t value);

  private:
  ::int32_t _internal_parity() const;
  void _internal_set_parity(::int32_t value);

  public:
  // int32 flow = 5;
  void clear_flow() ;
  [[nodiscard]] ::int32_t flow() const;
  void set_flow(::int32_t value);

  private:
  ::int32_t _internal_flow() const;
  void _internal_set_flow(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:bus.portCh)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const portCh& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t baud_;
    ::int32_t data_;
    ::int32_t stop_;
    ::int32_t parity_;
    ::int32_t flow_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_message_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull portCh_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED IoConfig final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:bus.IoConfig) */ {
 public:
  inline IoConfig() : IoConfig(nullptr) {}
  ~IoConfig() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(IoConfig* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(IoConfig));
  }
#endif

  template <typename = void>
  explicit constexpr IoConfig(::google::protobuf::internal::ConstantInitialized);

  inline IoConfig(const IoConfig& from) : IoConfig(nullptr, from) {}
  inline IoConfig(IoConfig&& from) noexcept
      : IoConfig(nullptr, ::std::move(from)) {}
  inline IoConfig& operator=(const IoConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline IoConfig& operator=(IoConfig&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const IoConfig& default_instance() {
    return *reinterpret_cast<const IoConfig*>(
        &_IoConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(IoConfig& a, IoConfig& b) { a.Swap(&b); }
  inline void Swap(IoConfig* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IoConfig* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] IoConfig* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<IoConfig>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const IoConfig& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const IoConfig& from) { IoConfig::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(IoConfig* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "bus.IoConfig"; }

  explicit IoConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  IoConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const IoConfig& from);
  IoConfig(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, IoConfig&& from) noexcept
      : IoConfig(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDevFieldNumber = 1,
    kOwnDevFieldNumber = 3,
    kOwnChFieldNumber = 4,
    kChFieldNumber = 2,
  };
  // string dev = 1;
  void clear_dev() ;
  [[nodiscard]] const ::std::string& dev() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_dev(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_dev();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_dev();
  void set_allocated_dev(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_dev() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_dev(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_dev();

  public:
  // string own_dev = 3;
  void clear_own_dev() ;
  [[nodiscard]] const ::std::string& own_dev() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_own_dev(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_own_dev();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_own_dev();
  void set_allocated_own_dev(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_own_dev() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_own_dev(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_own_dev();

  public:
  // string own_ch = 4;
  void clear_own_ch() ;
  [[nodiscard]] const ::std::string& own_ch() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_own_ch(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_own_ch();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_own_ch();
  void set_allocated_own_ch(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_own_ch() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_own_ch(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_own_ch();

  public:
  // .bus.portCh ch = 2;
  [[nodiscard]] bool has_ch()
      const;
  void clear_ch() ;
  [[nodiscard]] const ::bus::portCh& ch() const;
  [[nodiscard]] ::bus::portCh* PROTOBUF_NULLABLE release_ch();
  ::bus::portCh* PROTOBUF_NONNULL mutable_ch();
  void set_allocated_ch(::bus::portCh* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_ch(::bus::portCh* PROTOBUF_NULLABLE value);
  ::bus::portCh* PROTOBUF_NULLABLE unsafe_arena_release_ch();

  private:
  const ::bus::portCh& _internal_ch() const;
  ::bus::portCh* PROTOBUF_NONNULL _internal_mutable_ch();

  public:
  // @@protoc_insertion_point(class_scope:bus.IoConfig)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   1, 37,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const IoConfig& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr dev_;
    ::google::protobuf::internal::ArenaStringPtr own_dev_;
    ::google::protobuf::internal::ArenaStringPtr own_ch_;
    ::bus::portCh* PROTOBUF_NULLABLE ch_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_message_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull IoConfig_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// portCh

// int32 baud = 1;
inline void portCh::clear_baud() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.baud_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t portCh::baud() const {
  // @@protoc_insertion_point(field_get:bus.portCh.baud)
  return _internal_baud();
}
inline void portCh::set_baud(::int32_t value) {
  _internal_set_baud(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:bus.portCh.baud)
}
inline ::int32_t portCh::_internal_baud() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.baud_;
}
inline void portCh::_internal_set_baud(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.baud_ = value;
}

// int32 data = 2;
inline void portCh::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t portCh::data() const {
  // @@protoc_insertion_point(field_get:bus.portCh.data)
  return _internal_data();
}
inline void portCh::set_data(::int32_t value) {
  _internal_set_data(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:bus.portCh.data)
}
inline ::int32_t portCh::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_;
}
inline void portCh::_internal_set_data(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_ = value;
}

// int32 stop = 3;
inline void portCh::clear_stop() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stop_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t portCh::stop() const {
  // @@protoc_insertion_point(field_get:bus.portCh.stop)
  return _internal_stop();
}
inline void portCh::set_stop(::int32_t value) {
  _internal_set_stop(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:bus.portCh.stop)
}
inline ::int32_t portCh::_internal_stop() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.stop_;
}
inline void portCh::_internal_set_stop(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stop_ = value;
}

// int32 parity = 4;
inline void portCh::clear_parity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.parity_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t portCh::parity() const {
  // @@protoc_insertion_point(field_get:bus.portCh.parity)
  return _internal_parity();
}
inline void portCh::set_parity(::int32_t value) {
  _internal_set_parity(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:bus.portCh.parity)
}
inline ::int32_t portCh::_internal_parity() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.parity_;
}
inline void portCh::_internal_set_parity(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.parity_ = value;
}

// int32 flow = 5;
inline void portCh::clear_flow() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.flow_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::int32_t portCh::flow() const {
  // @@protoc_insertion_point(field_get:bus.portCh.flow)
  return _internal_flow();
}
inline void portCh::set_flow(::int32_t value) {
  _internal_set_flow(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:bus.portCh.flow)
}
inline ::int32_t portCh::_internal_flow() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.flow_;
}
inline void portCh::_internal_set_flow(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.flow_ = value;
}

// -------------------------------------------------------------------

// IoConfig

// string dev = 1;
inline void IoConfig::clear_dev() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dev_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& IoConfig::dev() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:bus.IoConfig.dev)
  return _internal_dev();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void IoConfig::set_dev(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.dev_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:bus.IoConfig.dev)
}
inline ::std::string* PROTOBUF_NONNULL IoConfig::mutable_dev()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_dev();
  // @@protoc_insertion_point(field_mutable:bus.IoConfig.dev)
  return _s;
}
inline const ::std::string& IoConfig::_internal_dev() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dev_.Get();
}
inline void IoConfig::_internal_set_dev(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dev_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL IoConfig::_internal_mutable_dev() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.dev_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE IoConfig::release_dev() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:bus.IoConfig.dev)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.dev_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.dev_.Set("", GetArena());
  }
  return released;
}
inline void IoConfig::set_allocated_dev(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.dev_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.dev_.IsDefault()) {
    _impl_.dev_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:bus.IoConfig.dev)
}

// .bus.portCh ch = 2;
inline bool IoConfig::has_ch() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  PROTOBUF_ASSUME(!value || _impl_.ch_ != nullptr);
  return value;
}
inline void IoConfig::clear_ch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.ch_ != nullptr) _impl_.ch_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::bus::portCh& IoConfig::_internal_ch() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::bus::portCh* p = _impl_.ch_;
  return p != nullptr ? *p : reinterpret_cast<const ::bus::portCh&>(::bus::_portCh_default_instance_);
}
inline const ::bus::portCh& IoConfig::ch() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:bus.IoConfig.ch)
  return _internal_ch();
}
inline void IoConfig::unsafe_arena_set_allocated_ch(
    ::bus::portCh* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.ch_);
  }
  _impl_.ch_ = reinterpret_cast<::bus::portCh*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:bus.IoConfig.ch)
}
inline ::bus::portCh* PROTOBUF_NULLABLE IoConfig::release_ch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::bus::portCh* released = _impl_.ch_;
  _impl_.ch_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::bus::portCh* PROTOBUF_NULLABLE IoConfig::unsafe_arena_release_ch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:bus.IoConfig.ch)

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::bus::portCh* temp = _impl_.ch_;
  _impl_.ch_ = nullptr;
  return temp;
}
inline ::bus::portCh* PROTOBUF_NONNULL IoConfig::_internal_mutable_ch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.ch_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::bus::portCh>(GetArena());
    _impl_.ch_ = reinterpret_cast<::bus::portCh*>(p);
  }
  return _impl_.ch_;
}
inline ::bus::portCh* PROTOBUF_NONNULL IoConfig::mutable_ch()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::bus::portCh* _msg = _internal_mutable_ch();
  // @@protoc_insertion_point(field_mutable:bus.IoConfig.ch)
  return _msg;
}
inline void IoConfig::set_allocated_ch(::bus::portCh* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.ch_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }

  _impl_.ch_ = reinterpret_cast<::bus::portCh*>(value);
  // @@protoc_insertion_point(field_set_allocated:bus.IoConfig.ch)
}

// string own_dev = 3;
inline void IoConfig::clear_own_dev() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.own_dev_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& IoConfig::own_dev() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:bus.IoConfig.own_dev)
  return _internal_own_dev();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void IoConfig::set_own_dev(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.own_dev_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:bus.IoConfig.own_dev)
}
inline ::std::string* PROTOBUF_NONNULL IoConfig::mutable_own_dev()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_own_dev();
  // @@protoc_insertion_point(field_mutable:bus.IoConfig.own_dev)
  return _s;
}
inline const ::std::string& IoConfig::_internal_own_dev() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.own_dev_.Get();
}
inline void IoConfig::_internal_set_own_dev(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.own_dev_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL IoConfig::_internal_mutable_own_dev() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.own_dev_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE IoConfig::release_own_dev() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:bus.IoConfig.own_dev)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.own_dev_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.own_dev_.Set("", GetArena());
  }
  return released;
}
inline void IoConfig::set_allocated_own_dev(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.own_dev_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.own_dev_.IsDefault()) {
    _impl_.own_dev_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:bus.IoConfig.own_dev)
}

// string own_ch = 4;
inline void IoConfig::clear_own_ch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.own_ch_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& IoConfig::own_ch() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:bus.IoConfig.own_ch)
  return _internal_own_ch();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void IoConfig::set_own_ch(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.own_ch_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:bus.IoConfig.own_ch)
}
inline ::std::string* PROTOBUF_NONNULL IoConfig::mutable_own_ch()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_own_ch();
  // @@protoc_insertion_point(field_mutable:bus.IoConfig.own_ch)
  return _s;
}
inline const ::std::string& IoConfig::_internal_own_ch() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.own_ch_.Get();
}
inline void IoConfig::_internal_set_own_ch(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.own_ch_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL IoConfig::_internal_mutable_own_ch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.own_ch_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE IoConfig::release_own_ch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:bus.IoConfig.own_ch)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.own_ch_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.own_ch_.Set("", GetArena());
  }
  return released;
}
inline void IoConfig::set_allocated_own_ch(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.own_ch_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.own_ch_.IsDefault()) {
    _impl_.own_ch_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:bus.IoConfig.own_ch)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace bus


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // message_2eproto_2epb_2eh
