// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message.proto
// Protobuf C++ Version: 7.34.1

#include "message.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace bus {

inline constexpr portCh::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        baud_{0},
        data_{0},
        stop_{0},
        parity_{0},
        flow_{0} {}

template <typename>
constexpr portCh::portCh(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(portCh_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct portChDefaultTypeInternal {
  constexpr portChDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~portChDefaultTypeInternal() {}
  union {
    portCh _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 portChDefaultTypeInternal _portCh_default_instance_;

inline constexpr IoConfig::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        dev_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        own_dev_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        own_ch_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        ch_{nullptr} {}

template <typename>
constexpr IoConfig::IoConfig(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(IoConfig_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct IoConfigDefaultTypeInternal {
  constexpr IoConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~IoConfigDefaultTypeInternal() {}
  union {
    IoConfig _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IoConfigDefaultTypeInternal _IoConfig_default_instance_;
}  // namespace bus
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_message_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_message_2eproto = nullptr;
const ::uint32_t
    TableStruct_message_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::bus::portCh, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::bus::portCh, _impl_.baud_),
        PROTOBUF_FIELD_OFFSET(::bus::portCh, _impl_.data_),
        PROTOBUF_FIELD_OFFSET(::bus::portCh, _impl_.stop_),
        PROTOBUF_FIELD_OFFSET(::bus::portCh, _impl_.parity_),
        PROTOBUF_FIELD_OFFSET(::bus::portCh, _impl_.flow_),
        0,
        1,
        2,
        3,
        4,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::bus::IoConfig, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::bus::IoConfig, _impl_.dev_),
        PROTOBUF_FIELD_OFFSET(::bus::IoConfig, _impl_.ch_),
        PROTOBUF_FIELD_OFFSET(::bus::IoConfig, _impl_.own_dev_),
        PROTOBUF_FIELD_OFFSET(::bus::IoConfig, _impl_.own_ch_),
        0,
        3,
        1,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::bus::portCh)},
        {13, sizeof(::bus::IoConfig)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::bus::_portCh_default_instance_._instance,
    &::bus::_IoConfig_default_instance_._instance,
};
const char descriptor_table_protodef_message_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\rmessage.proto\022\003bus\"P\n\006portCh\022\014\n\004baud\030\001"
    " \001(\005\022\014\n\004data\030\002 \001(\005\022\014\n\004stop\030\003 \001(\005\022\016\n\006pari"
    "ty\030\004 \001(\005\022\014\n\004flow\030\005 \001(\005\"Q\n\010IoConfig\022\013\n\003de"
    "v\030\001 \001(\t\022\027\n\002ch\030\002 \001(\0132\013.bus.portCh\022\017\n\007own_"
    "dev\030\003 \001(\t\022\016\n\006own_ch\030\004 \001(\tb\006proto3"
};
static ::absl::once_flag descriptor_table_message_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_message_2eproto = {
    false,
    false,
    193,
    descriptor_table_protodef_message_2eproto,
    "message.proto",
    &descriptor_table_message_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_message_2eproto::offsets,
    file_level_enum_descriptors_message_2eproto,
    file_level_service_descriptors_message_2eproto,
};
namespace bus {
// ===================================================================

class portCh::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<portCh>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(portCh, _impl_._has_bits_);
};

portCh::portCh(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, portCh_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:bus.portCh)
}
portCh::portCh(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const portCh& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, portCh_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE portCh::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void portCh::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, baud_),
           0,
           offsetof(Impl_, flow_) -
               offsetof(Impl_, baud_) +
               sizeof(Impl_::flow_));
}
portCh::~portCh() {
  // @@protoc_insertion_point(destructor:bus.portCh)
  SharedDtor(*this);
}
inline void portCh::SharedDtor(MessageLite& self) {
  portCh& this_ = static_cast<portCh&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL portCh::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) portCh(arena);
}
constexpr auto portCh::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(portCh),
                                            alignof(portCh));
}
constexpr auto portCh::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_portCh_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &portCh::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<portCh>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &portCh::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<portCh>(), &portCh::ByteSizeLong,
              &portCh::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(portCh, _impl_._cached_size_),
          false,
      },
      &portCh::kDescriptorMethods,
      &descriptor_table_message_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull portCh_class_data_ =
        portCh::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
portCh::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&portCh_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(portCh_class_data_.tc_table);
  return portCh_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2>
portCh::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(portCh, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    portCh_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::bus::portCh>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 baud = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(portCh, _impl_.baud_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(portCh, _impl_.baud_)}},
    // int32 data = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(portCh, _impl_.data_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(portCh, _impl_.data_)}},
    // int32 stop = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(portCh, _impl_.stop_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(portCh, _impl_.stop_)}},
    // int32 parity = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(portCh, _impl_.parity_), 3>(),
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(portCh, _impl_.parity_)}},
    // int32 flow = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(portCh, _impl_.flow_), 4>(),
     {40, 4, 0,
      PROTOBUF_FIELD_OFFSET(portCh, _impl_.flow_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 baud = 1;
    {PROTOBUF_FIELD_OFFSET(portCh, _impl_.baud_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 data = 2;
    {PROTOBUF_FIELD_OFFSET(portCh, _impl_.data_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 stop = 3;
    {PROTOBUF_FIELD_OFFSET(portCh, _impl_.stop_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 parity = 4;
    {PROTOBUF_FIELD_OFFSET(portCh, _impl_.parity_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 flow = 5;
    {PROTOBUF_FIELD_OFFSET(portCh, _impl_.flow_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void portCh::Clear() {
// @@protoc_insertion_point(message_clear_start:bus.portCh)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    ::memset(&_impl_.baud_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.flow_) -
        reinterpret_cast<char*>(&_impl_.baud_)) + sizeof(_impl_.flow_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL portCh::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const portCh& this_ = static_cast<const portCh&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL portCh::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const portCh& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:bus.portCh)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 baud = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_baud() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_baud(), target);
    }
  }

  // int32 data = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_data() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_data(), target);
    }
  }

  // int32 stop = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_stop() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_stop(), target);
    }
  }

  // int32 parity = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_parity() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<4>(
              stream, this_._internal_parity(), target);
    }
  }

  // int32 flow = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_flow() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<5>(
              stream, this_._internal_flow(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bus.portCh)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t portCh::ByteSizeLong(const MessageLite& base) {
  const portCh& this_ = static_cast<const portCh&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t portCh::ByteSizeLong() const {
  const portCh& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:bus.portCh)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // int32 baud = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_baud() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_baud());
      }
    }
    // int32 data = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_data() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_data());
      }
    }
    // int32 stop = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_stop() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_stop());
      }
    }
    // int32 parity = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_parity() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_parity());
      }
    }
    // int32 flow = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_flow() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_flow());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void portCh::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<portCh*>(&to_msg);
  auto& from = static_cast<const portCh&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:bus.portCh)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_baud() != 0) {
        _this->_impl_.baud_ = from._impl_.baud_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_data() != 0) {
        _this->_impl_.data_ = from._impl_.data_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_stop() != 0) {
        _this->_impl_.stop_ = from._impl_.stop_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_parity() != 0) {
        _this->_impl_.parity_ = from._impl_.parity_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_flow() != 0) {
        _this->_impl_.flow_ = from._impl_.flow_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void portCh::CopyFrom(const portCh& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:bus.portCh)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void portCh::InternalSwap(portCh* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(portCh, _impl_.flow_)
      + sizeof(portCh::_impl_.flow_)
      - PROTOBUF_FIELD_OFFSET(portCh, _impl_.baud_)>(
          reinterpret_cast<char*>(&_impl_.baud_),
          reinterpret_cast<char*>(&other->_impl_.baud_));
}

::google::protobuf::Metadata portCh::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class IoConfig::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<IoConfig>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(IoConfig, _impl_._has_bits_);
};

IoConfig::IoConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, IoConfig_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:bus.IoConfig)
}
PROTOBUF_NDEBUG_INLINE IoConfig::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::bus::IoConfig& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        dev_(arena, from.dev_),
        own_dev_(arena, from.own_dev_),
        own_ch_(arena, from.own_ch_) {}

IoConfig::IoConfig(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const IoConfig& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, IoConfig_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  IoConfig* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.ch_ = (CheckHasBit(cached_has_bits, 0x00000008U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.ch_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:bus.IoConfig)
}
PROTOBUF_NDEBUG_INLINE IoConfig::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        dev_(arena),
        own_dev_(arena),
        own_ch_(arena) {}

inline void IoConfig::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.ch_ = {};
}
IoConfig::~IoConfig() {
  // @@protoc_insertion_point(destructor:bus.IoConfig)
  SharedDtor(*this);
}
inline void IoConfig::SharedDtor(MessageLite& self) {
  IoConfig& this_ = static_cast<IoConfig&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.dev_.Destroy();
  this_._impl_.own_dev_.Destroy();
  this_._impl_.own_ch_.Destroy();
  delete this_._impl_.ch_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL IoConfig::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) IoConfig(arena);
}
constexpr auto IoConfig::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(IoConfig),
                                            alignof(IoConfig));
}
constexpr auto IoConfig::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_IoConfig_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &IoConfig::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<IoConfig>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &IoConfig::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<IoConfig>(), &IoConfig::ByteSizeLong,
              &IoConfig::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(IoConfig, _impl_._cached_size_),
          false,
      },
      &IoConfig::kDescriptorMethods,
      &descriptor_table_message_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull IoConfig_class_data_ =
        IoConfig::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
IoConfig::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&IoConfig_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(IoConfig_class_data_.tc_table);
  return IoConfig_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 37, 2>
IoConfig::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(IoConfig, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    IoConfig_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::bus::IoConfig>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string own_ch = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 2, 0,
      PROTOBUF_FIELD_OFFSET(IoConfig, _impl_.own_ch_)}},
    // string dev = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(IoConfig, _impl_.dev_)}},
    // .bus.portCh ch = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 3, 0,
      PROTOBUF_FIELD_OFFSET(IoConfig, _impl_.ch_)}},
    // string own_dev = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(IoConfig, _impl_.own_dev_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string dev = 1;
    {PROTOBUF_FIELD_OFFSET(IoConfig, _impl_.dev_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .bus.portCh ch = 2;
    {PROTOBUF_FIELD_OFFSET(IoConfig, _impl_.ch_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string own_dev = 3;
    {PROTOBUF_FIELD_OFFSET(IoConfig, _impl_.own_dev_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string own_ch = 4;
    {PROTOBUF_FIELD_OFFSET(IoConfig, _impl_.own_ch_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::bus::portCh>()},
  }},
  {{
    "\14\3\0\7\6\0\0\0"
    "bus.IoConfig"
    "dev"
    "own_dev"
    "own_ch"
  }},
};
PROTOBUF_NOINLINE void IoConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:bus.IoConfig)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.dev_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.own_dev_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.own_ch_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(_impl_.ch_ != nullptr);
      _impl_.ch_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL IoConfig::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const IoConfig& this_ = static_cast<const IoConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL IoConfig::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const IoConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:bus.IoConfig)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string dev = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_dev().empty()) {
      const ::std::string& _s = this_._internal_dev();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "bus.IoConfig.dev");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // .bus.portCh ch = 2;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.ch_, this_._impl_.ch_->GetCachedSize(), target,
        stream);
  }

  // string own_dev = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_own_dev().empty()) {
      const ::std::string& _s = this_._internal_own_dev();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "bus.IoConfig.own_dev");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // string own_ch = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_own_ch().empty()) {
      const ::std::string& _s = this_._internal_own_ch();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "bus.IoConfig.own_ch");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bus.IoConfig)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t IoConfig::ByteSizeLong(const MessageLite& base) {
  const IoConfig& this_ = static_cast<const IoConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t IoConfig::ByteSizeLong() const {
  const IoConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:bus.IoConfig)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // string dev = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_dev().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_dev());
      }
    }
    // string own_dev = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_own_dev().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_own_dev());
      }
    }
    // string own_ch = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_own_ch().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_own_ch());
      }
    }
    // .bus.portCh ch = 2;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.ch_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void IoConfig::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<IoConfig*>(&to_msg);
  auto& from = static_cast<const IoConfig&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:bus.IoConfig)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_dev().empty()) {
        _this->_internal_set_dev(from._internal_dev());
      } else {
        if (_this->_impl_.dev_.IsDefault()) {
          _this->_internal_set_dev("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_own_dev().empty()) {
        _this->_internal_set_own_dev(from._internal_own_dev());
      } else {
        if (_this->_impl_.own_dev_.IsDefault()) {
          _this->_internal_set_own_dev("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_own_ch().empty()) {
        _this->_internal_set_own_ch(from._internal_own_ch());
      } else {
        if (_this->_impl_.own_ch_.IsDefault()) {
          _this->_internal_set_own_ch("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(from._impl_.ch_ != nullptr);
      if (_this->_impl_.ch_ == nullptr) {
        _this->_impl_.ch_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.ch_);
      } else {
        _this->_impl_.ch_->MergeFrom(*from._impl_.ch_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void IoConfig::CopyFrom(const IoConfig& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:bus.IoConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void IoConfig::InternalSwap(IoConfig* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.dev_, &other->_impl_.dev_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.own_dev_, &other->_impl_.own_dev_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.own_ch_, &other->_impl_.own_ch_, arena);
  swap(_impl_.ch_, other->_impl_.ch_);
}

::google::protobuf::Metadata IoConfig::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace bus
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_message_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
